// Code generated by bitproto. DO NOT EDIT.

#include "example_bp.h"
#include <string.h>

int EncodePropeller(struct Propeller *m, unsigned char *s) {
    s[0] = ((uint8_t)((*m).id)) & 255;
    s[1] = ((uint8_t)((*m).status)) & 3;
    s[1] |= ((uint8_t)((*m).direction)<< 2) & 12;
    return 0;
}

int DecodePropeller(struct Propeller *m, unsigned char *s) {
    memset(m, 0, sizeof(*m));
    (*m).id |= (uint8_t)(((unsigned)(s[0])) & 255);
    (*m).status |= (PropellerStatus)(((unsigned)(s[1])) & 3);
    (*m).direction |= (RotatingDirection)(((unsigned)(s[1])>> 2) & 3);
    return 0;
}

int EncodePower(struct Power *m, unsigned char *s) {
    s[0] = ((uint8_t)((*m).battery)) & 255;
    s[1] = ((uint8_t)((*m).status)) & 3;
    s[1] |= ((uint8_t)((*m).is_charging)<< 2) & 4;
    return 0;
}

int DecodePower(struct Power *m, unsigned char *s) {
    memset(m, 0, sizeof(*m));
    (*m).battery |= (uint8_t)(((unsigned)(s[0])) & 255);
    (*m).status |= (PowerStatus)(((unsigned)(s[1])) & 3);
    (*m).is_charging |= (bool)(((unsigned)(s[1])>> 2) & 1);
    return 0;
}

int EncodeNetwork(struct Network *m, unsigned char *s) {
    s[0] = ((uint8_t)((*m).signal)) & 15;
    s[0] |= ((uint32_t)((*m).heartbeat_at)<< 4) & 240;
    s[1] = ((uint32_t)((*m).heartbeat_at)>> 4) & 15;
    s[1] |= ((uint32_t)((*m).heartbeat_at)>> 4) & 240;
    s[2] = ((uint32_t)((*m).heartbeat_at)>> 12) & 15;
    s[2] |= ((uint32_t)((*m).heartbeat_at)>> 12) & 240;
    s[3] = ((uint32_t)((*m).heartbeat_at)>> 20) & 15;
    s[3] |= ((uint32_t)((*m).heartbeat_at)>> 20) & 240;
    s[4] = ((uint32_t)((*m).heartbeat_at)>> 28) & 15;
    return 0;
}

int DecodeNetwork(struct Network *m, unsigned char *s) {
    memset(m, 0, sizeof(*m));
    (*m).signal |= (uint8_t)(((unsigned)(s[0])) & 15);
    (*m).heartbeat_at |= (Timestamp)(((unsigned)(s[0])>> 4) & 15);
    (*m).heartbeat_at |= (Timestamp)(((unsigned)(s[1])<< 4) & 240);
    (*m).heartbeat_at |= (Timestamp)((uint32_t)(((unsigned)(s[1])>> 4) & 15) << 8);
    (*m).heartbeat_at |= (Timestamp)((uint32_t)(((unsigned)(s[2])<< 4) & 240) << 8);
    (*m).heartbeat_at |= (Timestamp)((uint32_t)(((unsigned)(s[2])>> 4) & 15) << 16);
    (*m).heartbeat_at |= (Timestamp)((uint32_t)(((unsigned)(s[3])<< 4) & 240) << 16);
    (*m).heartbeat_at |= (Timestamp)((uint32_t)(((unsigned)(s[3])>> 4) & 15) << 24);
    (*m).heartbeat_at |= (Timestamp)((uint32_t)(((unsigned)(s[4])<< 4) & 240) << 24);
    return 0;
}

int EncodeLandingGear(struct LandingGear *m, unsigned char *s) {
    s[0] = ((uint8_t)((*m).status)) & 3;
    return 0;
}

int DecodeLandingGear(struct LandingGear *m, unsigned char *s) {
    memset(m, 0, sizeof(*m));
    (*m).status |= (LandingGearStatus)(((unsigned)(s[0])) & 3);
    return 0;
}

int EncodePosition(struct Position *m, unsigned char *s) {
    s[0] = ((uint32_t)((*m).latitude)) & 255;
    s[1] = ((uint32_t)((*m).latitude)>> 8) & 255;
    s[2] = ((uint32_t)((*m).latitude)>> 16) & 255;
    s[3] = ((uint32_t)((*m).latitude)>> 24) & 255;
    s[4] = ((uint32_t)((*m).longitude)) & 255;
    s[5] = ((uint32_t)((*m).longitude)>> 8) & 255;
    s[6] = ((uint32_t)((*m).longitude)>> 16) & 255;
    s[7] = ((uint32_t)((*m).longitude)>> 24) & 255;
    s[8] = ((uint32_t)((*m).altitude)) & 255;
    s[9] = ((uint32_t)((*m).altitude)>> 8) & 255;
    s[10] = ((uint32_t)((*m).altitude)>> 16) & 255;
    s[11] = ((uint32_t)((*m).altitude)>> 24) & 255;
    return 0;
}

int DecodePosition(struct Position *m, unsigned char *s) {
    memset(m, 0, sizeof(*m));
    (*m).latitude |= (uint32_t)(((unsigned)(s[0])) & 255);
    (*m).latitude |= (uint32_t)((uint32_t)(((unsigned)(s[1])) & 255) << 8);
    (*m).latitude |= (uint32_t)((uint32_t)(((unsigned)(s[2])) & 255) << 16);
    (*m).latitude |= (uint32_t)((uint32_t)(((unsigned)(s[3])) & 255) << 24);
    (*m).longitude |= (uint32_t)(((unsigned)(s[4])) & 255);
    (*m).longitude |= (uint32_t)((uint32_t)(((unsigned)(s[5])) & 255) << 8);
    (*m).longitude |= (uint32_t)((uint32_t)(((unsigned)(s[6])) & 255) << 16);
    (*m).longitude |= (uint32_t)((uint32_t)(((unsigned)(s[7])) & 255) << 24);
    (*m).altitude |= (uint32_t)(((unsigned)(s[8])) & 255);
    (*m).altitude |= (uint32_t)((uint32_t)(((unsigned)(s[9])) & 255) << 8);
    (*m).altitude |= (uint32_t)((uint32_t)(((unsigned)(s[10])) & 255) << 16);
    (*m).altitude |= (uint32_t)((uint32_t)(((unsigned)(s[11])) & 255) << 24);
    return 0;
}

int EncodePose(struct Pose *m, unsigned char *s) {
    s[0] = ((uint32_t)((*m).yaw)) & 255;
    s[1] = ((uint32_t)((*m).yaw)>> 8) & 255;
    s[2] = ((uint32_t)((*m).yaw)>> 16) & 255;
    s[3] = ((uint32_t)((*m).yaw)>> 24) & 255;
    s[4] = ((uint32_t)((*m).pitch)) & 255;
    s[5] = ((uint32_t)((*m).pitch)>> 8) & 255;
    s[6] = ((uint32_t)((*m).pitch)>> 16) & 255;
    s[7] = ((uint32_t)((*m).pitch)>> 24) & 255;
    s[8] = ((uint32_t)((*m).roll)) & 255;
    s[9] = ((uint32_t)((*m).roll)>> 8) & 255;
    s[10] = ((uint32_t)((*m).roll)>> 16) & 255;
    s[11] = ((uint32_t)((*m).roll)>> 24) & 255;
    return 0;
}

int DecodePose(struct Pose *m, unsigned char *s) {
    memset(m, 0, sizeof(*m));
    (*m).yaw |= (int32_t)(((unsigned)(s[0])) & 255);
    (*m).yaw |= (int32_t)((uint32_t)(((unsigned)(s[1])) & 255) << 8);
    (*m).yaw |= (int32_t)((uint32_t)(((unsigned)(s[2])) & 255) << 16);
    (*m).yaw |= (int32_t)((uint32_t)(((unsigned)(s[3])) & 255) << 24);
    (*m).pitch |= (int32_t)(((unsigned)(s[4])) & 255);
    (*m).pitch |= (int32_t)((uint32_t)(((unsigned)(s[5])) & 255) << 8);
    (*m).pitch |= (int32_t)((uint32_t)(((unsigned)(s[6])) & 255) << 16);
    (*m).pitch |= (int32_t)((uint32_t)(((unsigned)(s[7])) & 255) << 24);
    (*m).roll |= (int32_t)(((unsigned)(s[8])) & 255);
    (*m).roll |= (int32_t)((uint32_t)(((unsigned)(s[9])) & 255) << 8);
    (*m).roll |= (int32_t)((uint32_t)(((unsigned)(s[10])) & 255) << 16);
    (*m).roll |= (int32_t)((uint32_t)(((unsigned)(s[11])) & 255) << 24);
    return 0;
}

int EncodeFlight(struct Flight *m, unsigned char *s) {
    s[0] = ((uint32_t)((*m).pose.yaw)) & 255;
    s[1] = ((uint32_t)((*m).pose.yaw)>> 8) & 255;
    s[2] = ((uint32_t)((*m).pose.yaw)>> 16) & 255;
    s[3] = ((uint32_t)((*m).pose.yaw)>> 24) & 255;
    s[4] = ((uint32_t)((*m).pose.pitch)) & 255;
    s[5] = ((uint32_t)((*m).pose.pitch)>> 8) & 255;
    s[6] = ((uint32_t)((*m).pose.pitch)>> 16) & 255;
    s[7] = ((uint32_t)((*m).pose.pitch)>> 24) & 255;
    s[8] = ((uint32_t)((*m).pose.roll)) & 255;
    s[9] = ((uint32_t)((*m).pose.roll)>> 8) & 255;
    s[10] = ((uint32_t)((*m).pose.roll)>> 16) & 255;
    s[11] = ((uint32_t)((*m).pose.roll)>> 24) & 255;
    s[12] = ((uint32_t)((*m).velocity[0])) & 255;
    s[13] = ((uint32_t)((*m).velocity[0])>> 8) & 255;
    s[14] = ((uint32_t)((*m).velocity[0])>> 16) & 255;
    s[15] = ((uint32_t)((*m).velocity[0])>> 24) & 255;
    s[16] = ((uint32_t)((*m).velocity[1])) & 255;
    s[17] = ((uint32_t)((*m).velocity[1])>> 8) & 255;
    s[18] = ((uint32_t)((*m).velocity[1])>> 16) & 255;
    s[19] = ((uint32_t)((*m).velocity[1])>> 24) & 255;
    s[20] = ((uint32_t)((*m).velocity[2])) & 255;
    s[21] = ((uint32_t)((*m).velocity[2])>> 8) & 255;
    s[22] = ((uint32_t)((*m).velocity[2])>> 16) & 255;
    s[23] = ((uint32_t)((*m).velocity[2])>> 24) & 255;
    s[24] = ((uint32_t)((*m).acceleration[0])) & 255;
    s[25] = ((uint32_t)((*m).acceleration[0])>> 8) & 255;
    s[26] = ((uint32_t)((*m).acceleration[0])>> 16) & 255;
    s[27] = ((uint32_t)((*m).acceleration[0])>> 24) & 255;
    s[28] = ((uint32_t)((*m).acceleration[1])) & 255;
    s[29] = ((uint32_t)((*m).acceleration[1])>> 8) & 255;
    s[30] = ((uint32_t)((*m).acceleration[1])>> 16) & 255;
    s[31] = ((uint32_t)((*m).acceleration[1])>> 24) & 255;
    s[32] = ((uint32_t)((*m).acceleration[2])) & 255;
    s[33] = ((uint32_t)((*m).acceleration[2])>> 8) & 255;
    s[34] = ((uint32_t)((*m).acceleration[2])>> 16) & 255;
    s[35] = ((uint32_t)((*m).acceleration[2])>> 24) & 255;
    return 0;
}

int DecodeFlight(struct Flight *m, unsigned char *s) {
    memset(m, 0, sizeof(*m));
    (*m).pose.yaw |= (int32_t)(((unsigned)(s[0])) & 255);
    (*m).pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[1])) & 255) << 8);
    (*m).pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[2])) & 255) << 16);
    (*m).pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[3])) & 255) << 24);
    (*m).pose.pitch |= (int32_t)(((unsigned)(s[4])) & 255);
    (*m).pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[5])) & 255) << 8);
    (*m).pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[6])) & 255) << 16);
    (*m).pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[7])) & 255) << 24);
    (*m).pose.roll |= (int32_t)(((unsigned)(s[8])) & 255);
    (*m).pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[9])) & 255) << 8);
    (*m).pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[10])) & 255) << 16);
    (*m).pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[11])) & 255) << 24);
    (*m).velocity[0] |= (int32_t)(((unsigned)(s[12])) & 255);
    (*m).velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[13])) & 255) << 8);
    (*m).velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[14])) & 255) << 16);
    (*m).velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[15])) & 255) << 24);
    (*m).velocity[1] |= (int32_t)(((unsigned)(s[16])) & 255);
    (*m).velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[17])) & 255) << 8);
    (*m).velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[18])) & 255) << 16);
    (*m).velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[19])) & 255) << 24);
    (*m).velocity[2] |= (int32_t)(((unsigned)(s[20])) & 255);
    (*m).velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[21])) & 255) << 8);
    (*m).velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[22])) & 255) << 16);
    (*m).velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[23])) & 255) << 24);
    (*m).acceleration[0] |= (int32_t)(((unsigned)(s[24])) & 255);
    (*m).acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[25])) & 255) << 8);
    (*m).acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[26])) & 255) << 16);
    (*m).acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[27])) & 255) << 24);
    (*m).acceleration[1] |= (int32_t)(((unsigned)(s[28])) & 255);
    (*m).acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[29])) & 255) << 8);
    (*m).acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[30])) & 255) << 16);
    (*m).acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[31])) & 255) << 24);
    (*m).acceleration[2] |= (int32_t)(((unsigned)(s[32])) & 255);
    (*m).acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[33])) & 255) << 8);
    (*m).acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[34])) & 255) << 16);
    (*m).acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[35])) & 255) << 24);
    return 0;
}

int EncodePressureSensor(struct PressureSensor *m, unsigned char *s) {
    s[0] = ((uint32_t)((*m).pressures[0])) & 255;
    s[1] = ((uint32_t)((*m).pressures[0])>> 8) & 255;
    s[2] = ((uint32_t)((*m).pressures[0])>> 16) & 255;
    s[3] = ((uint32_t)((*m).pressures[1])) & 255;
    s[4] = ((uint32_t)((*m).pressures[1])>> 8) & 255;
    s[5] = ((uint32_t)((*m).pressures[1])>> 16) & 255;
    return 0;
}

int DecodePressureSensor(struct PressureSensor *m, unsigned char *s) {
    memset(m, 0, sizeof(*m));
    (*m).pressures[0] |= (int32_t)(((unsigned)(s[0])) & 255);
    (*m).pressures[0] |= (int32_t)((uint32_t)(((unsigned)(s[1])) & 255) << 8);
    (*m).pressures[0] |= (int32_t)((uint32_t)(((unsigned)(s[2])) & 255) << 16);
    if (((*m).pressures[0] >> 23) & 1) (*m).pressures[0] |= -16777216;
    (*m).pressures[1] |= (int32_t)(((unsigned)(s[3])) & 255);
    (*m).pressures[1] |= (int32_t)((uint32_t)(((unsigned)(s[4])) & 255) << 8);
    (*m).pressures[1] |= (int32_t)((uint32_t)(((unsigned)(s[5])) & 255) << 16);
    if (((*m).pressures[1] >> 23) & 1) (*m).pressures[1] |= -16777216;
    return 0;
}

int EncodeDrone(struct Drone *m, unsigned char *s) {
    s[0] = ((uint8_t)((*m).status)) & 7;
    s[0] |= ((uint32_t)((*m).position.latitude)<< 3) & 248;
    s[1] = ((uint32_t)((*m).position.latitude)>> 5) & 7;
    s[1] |= ((uint32_t)((*m).position.latitude)>> 5) & 248;
    s[2] = ((uint32_t)((*m).position.latitude)>> 13) & 7;
    s[2] |= ((uint32_t)((*m).position.latitude)>> 13) & 248;
    s[3] = ((uint32_t)((*m).position.latitude)>> 21) & 7;
    s[3] |= ((uint32_t)((*m).position.latitude)>> 21) & 248;
    s[4] = ((uint32_t)((*m).position.latitude)>> 29) & 7;
    s[4] |= ((uint32_t)((*m).position.longitude)<< 3) & 248;
    s[5] = ((uint32_t)((*m).position.longitude)>> 5) & 7;
    s[5] |= ((uint32_t)((*m).position.longitude)>> 5) & 248;
    s[6] = ((uint32_t)((*m).position.longitude)>> 13) & 7;
    s[6] |= ((uint32_t)((*m).position.longitude)>> 13) & 248;
    s[7] = ((uint32_t)((*m).position.longitude)>> 21) & 7;
    s[7] |= ((uint32_t)((*m).position.longitude)>> 21) & 248;
    s[8] = ((uint32_t)((*m).position.longitude)>> 29) & 7;
    s[8] |= ((uint32_t)((*m).position.altitude)<< 3) & 248;
    s[9] = ((uint32_t)((*m).position.altitude)>> 5) & 7;
    s[9] |= ((uint32_t)((*m).position.altitude)>> 5) & 248;
    s[10] = ((uint32_t)((*m).position.altitude)>> 13) & 7;
    s[10] |= ((uint32_t)((*m).position.altitude)>> 13) & 248;
    s[11] = ((uint32_t)((*m).position.altitude)>> 21) & 7;
    s[11] |= ((uint32_t)((*m).position.altitude)>> 21) & 248;
    s[12] = ((uint32_t)((*m).position.altitude)>> 29) & 7;
    s[12] |= ((uint32_t)((*m).flight.pose.yaw)<< 3) & 248;
    s[13] = ((uint32_t)((*m).flight.pose.yaw)>> 5) & 7;
    s[13] |= ((uint32_t)((*m).flight.pose.yaw)>> 5) & 248;
    s[14] = ((uint32_t)((*m).flight.pose.yaw)>> 13) & 7;
    s[14] |= ((uint32_t)((*m).flight.pose.yaw)>> 13) & 248;
    s[15] = ((uint32_t)((*m).flight.pose.yaw)>> 21) & 7;
    s[15] |= ((uint32_t)((*m).flight.pose.yaw)>> 21) & 248;
    s[16] = ((uint32_t)((*m).flight.pose.yaw)>> 29) & 7;
    s[16] |= ((uint32_t)((*m).flight.pose.pitch)<< 3) & 248;
    s[17] = ((uint32_t)((*m).flight.pose.pitch)>> 5) & 7;
    s[17] |= ((uint32_t)((*m).flight.pose.pitch)>> 5) & 248;
    s[18] = ((uint32_t)((*m).flight.pose.pitch)>> 13) & 7;
    s[18] |= ((uint32_t)((*m).flight.pose.pitch)>> 13) & 248;
    s[19] = ((uint32_t)((*m).flight.pose.pitch)>> 21) & 7;
    s[19] |= ((uint32_t)((*m).flight.pose.pitch)>> 21) & 248;
    s[20] = ((uint32_t)((*m).flight.pose.pitch)>> 29) & 7;
    s[20] |= ((uint32_t)((*m).flight.pose.roll)<< 3) & 248;
    s[21] = ((uint32_t)((*m).flight.pose.roll)>> 5) & 7;
    s[21] |= ((uint32_t)((*m).flight.pose.roll)>> 5) & 248;
    s[22] = ((uint32_t)((*m).flight.pose.roll)>> 13) & 7;
    s[22] |= ((uint32_t)((*m).flight.pose.roll)>> 13) & 248;
    s[23] = ((uint32_t)((*m).flight.pose.roll)>> 21) & 7;
    s[23] |= ((uint32_t)((*m).flight.pose.roll)>> 21) & 248;
    s[24] = ((uint32_t)((*m).flight.pose.roll)>> 29) & 7;
    s[24] |= ((uint32_t)((*m).flight.velocity[0])<< 3) & 248;
    s[25] = ((uint32_t)((*m).flight.velocity[0])>> 5) & 7;
    s[25] |= ((uint32_t)((*m).flight.velocity[0])>> 5) & 248;
    s[26] = ((uint32_t)((*m).flight.velocity[0])>> 13) & 7;
    s[26] |= ((uint32_t)((*m).flight.velocity[0])>> 13) & 248;
    s[27] = ((uint32_t)((*m).flight.velocity[0])>> 21) & 7;
    s[27] |= ((uint32_t)((*m).flight.velocity[0])>> 21) & 248;
    s[28] = ((uint32_t)((*m).flight.velocity[0])>> 29) & 7;
    s[28] |= ((uint32_t)((*m).flight.velocity[1])<< 3) & 248;
    s[29] = ((uint32_t)((*m).flight.velocity[1])>> 5) & 7;
    s[29] |= ((uint32_t)((*m).flight.velocity[1])>> 5) & 248;
    s[30] = ((uint32_t)((*m).flight.velocity[1])>> 13) & 7;
    s[30] |= ((uint32_t)((*m).flight.velocity[1])>> 13) & 248;
    s[31] = ((uint32_t)((*m).flight.velocity[1])>> 21) & 7;
    s[31] |= ((uint32_t)((*m).flight.velocity[1])>> 21) & 248;
    s[32] = ((uint32_t)((*m).flight.velocity[1])>> 29) & 7;
    s[32] |= ((uint32_t)((*m).flight.velocity[2])<< 3) & 248;
    s[33] = ((uint32_t)((*m).flight.velocity[2])>> 5) & 7;
    s[33] |= ((uint32_t)((*m).flight.velocity[2])>> 5) & 248;
    s[34] = ((uint32_t)((*m).flight.velocity[2])>> 13) & 7;
    s[34] |= ((uint32_t)((*m).flight.velocity[2])>> 13) & 248;
    s[35] = ((uint32_t)((*m).flight.velocity[2])>> 21) & 7;
    s[35] |= ((uint32_t)((*m).flight.velocity[2])>> 21) & 248;
    s[36] = ((uint32_t)((*m).flight.velocity[2])>> 29) & 7;
    s[36] |= ((uint32_t)((*m).flight.acceleration[0])<< 3) & 248;
    s[37] = ((uint32_t)((*m).flight.acceleration[0])>> 5) & 7;
    s[37] |= ((uint32_t)((*m).flight.acceleration[0])>> 5) & 248;
    s[38] = ((uint32_t)((*m).flight.acceleration[0])>> 13) & 7;
    s[38] |= ((uint32_t)((*m).flight.acceleration[0])>> 13) & 248;
    s[39] = ((uint32_t)((*m).flight.acceleration[0])>> 21) & 7;
    s[39] |= ((uint32_t)((*m).flight.acceleration[0])>> 21) & 248;
    s[40] = ((uint32_t)((*m).flight.acceleration[0])>> 29) & 7;
    s[40] |= ((uint32_t)((*m).flight.acceleration[1])<< 3) & 248;
    s[41] = ((uint32_t)((*m).flight.acceleration[1])>> 5) & 7;
    s[41] |= ((uint32_t)((*m).flight.acceleration[1])>> 5) & 248;
    s[42] = ((uint32_t)((*m).flight.acceleration[1])>> 13) & 7;
    s[42] |= ((uint32_t)((*m).flight.acceleration[1])>> 13) & 248;
    s[43] = ((uint32_t)((*m).flight.acceleration[1])>> 21) & 7;
    s[43] |= ((uint32_t)((*m).flight.acceleration[1])>> 21) & 248;
    s[44] = ((uint32_t)((*m).flight.acceleration[1])>> 29) & 7;
    s[44] |= ((uint32_t)((*m).flight.acceleration[2])<< 3) & 248;
    s[45] = ((uint32_t)((*m).flight.acceleration[2])>> 5) & 7;
    s[45] |= ((uint32_t)((*m).flight.acceleration[2])>> 5) & 248;
    s[46] = ((uint32_t)((*m).flight.acceleration[2])>> 13) & 7;
    s[46] |= ((uint32_t)((*m).flight.acceleration[2])>> 13) & 248;
    s[47] = ((uint32_t)((*m).flight.acceleration[2])>> 21) & 7;
    s[47] |= ((uint32_t)((*m).flight.acceleration[2])>> 21) & 248;
    s[48] = ((uint32_t)((*m).flight.acceleration[2])>> 29) & 7;
    s[48] |= ((uint8_t)((*m).propellers[0].id)<< 3) & 248;
    s[49] = ((uint8_t)((*m).propellers[0].id)>> 5) & 7;
    s[49] |= ((uint8_t)((*m).propellers[0].status)<< 3) & 24;
    s[49] |= ((uint8_t)((*m).propellers[0].direction)<< 5) & 96;
    s[49] |= ((uint8_t)((*m).propellers[1].id)<< 7) & 128;
    s[50] = ((uint8_t)((*m).propellers[1].id)>> 1) & 127;
    s[50] |= ((uint8_t)((*m).propellers[1].status)<< 7) & 128;
    s[51] = ((uint8_t)((*m).propellers[1].status)>> 1) & 1;
    s[51] |= ((uint8_t)((*m).propellers[1].direction)<< 1) & 6;
    s[51] |= ((uint8_t)((*m).propellers[2].id)<< 3) & 248;
    s[52] = ((uint8_t)((*m).propellers[2].id)>> 5) & 7;
    s[52] |= ((uint8_t)((*m).propellers[2].status)<< 3) & 24;
    s[52] |= ((uint8_t)((*m).propellers[2].direction)<< 5) & 96;
    s[52] |= ((uint8_t)((*m).propellers[3].id)<< 7) & 128;
    s[53] = ((uint8_t)((*m).propellers[3].id)>> 1) & 127;
    s[53] |= ((uint8_t)((*m).propellers[3].status)<< 7) & 128;
    s[54] = ((uint8_t)((*m).propellers[3].status)>> 1) & 1;
    s[54] |= ((uint8_t)((*m).propellers[3].direction)<< 1) & 6;
    s[54] |= ((uint8_t)((*m).power.battery)<< 3) & 248;
    s[55] = ((uint8_t)((*m).power.battery)>> 5) & 7;
    s[55] |= ((uint8_t)((*m).power.status)<< 3) & 24;
    s[55] |= ((uint8_t)((*m).power.is_charging)<< 5) & 32;
    s[55] |= ((uint8_t)((*m).network.signal)<< 6) & 192;
    s[56] = ((uint8_t)((*m).network.signal)>> 2) & 3;
    s[56] |= ((uint32_t)((*m).network.heartbeat_at)<< 2) & 252;
    s[57] = ((uint32_t)((*m).network.heartbeat_at)>> 6) & 3;
    s[57] |= ((uint32_t)((*m).network.heartbeat_at)>> 6) & 252;
    s[58] = ((uint32_t)((*m).network.heartbeat_at)>> 14) & 3;
    s[58] |= ((uint32_t)((*m).network.heartbeat_at)>> 14) & 252;
    s[59] = ((uint32_t)((*m).network.heartbeat_at)>> 22) & 3;
    s[59] |= ((uint32_t)((*m).network.heartbeat_at)>> 22) & 252;
    s[60] = ((uint32_t)((*m).network.heartbeat_at)>> 30) & 3;
    s[60] |= ((uint8_t)((*m).landing_gear.status)<< 2) & 12;
    s[60] |= ((uint32_t)((*m).pressure_sensor.pressures[0])<< 4) & 240;
    s[61] = ((uint32_t)((*m).pressure_sensor.pressures[0])>> 4) & 15;
    s[61] |= ((uint32_t)((*m).pressure_sensor.pressures[0])>> 4) & 240;
    s[62] = ((uint32_t)((*m).pressure_sensor.pressures[0])>> 12) & 15;
    s[62] |= ((uint32_t)((*m).pressure_sensor.pressures[0])>> 12) & 240;
    s[63] = ((uint32_t)((*m).pressure_sensor.pressures[0])>> 20) & 15;
    s[63] |= ((uint32_t)((*m).pressure_sensor.pressures[1])<< 4) & 240;
    s[64] = ((uint32_t)((*m).pressure_sensor.pressures[1])>> 4) & 15;
    s[64] |= ((uint32_t)((*m).pressure_sensor.pressures[1])>> 4) & 240;
    s[65] = ((uint32_t)((*m).pressure_sensor.pressures[1])>> 12) & 15;
    s[65] |= ((uint32_t)((*m).pressure_sensor.pressures[1])>> 12) & 240;
    s[66] = ((uint32_t)((*m).pressure_sensor.pressures[1])>> 20) & 15;
    return 0;
}

int DecodeDrone(struct Drone *m, unsigned char *s) {
    memset(m, 0, sizeof(*m));
    (*m).status |= (DroneStatus)(((unsigned)(s[0])) & 7);
    (*m).position.latitude |= (uint32_t)(((unsigned)(s[0])>> 3) & 31);
    (*m).position.latitude |= (uint32_t)(((unsigned)(s[1])<< 5) & 224);
    (*m).position.latitude |= (uint32_t)((uint32_t)(((unsigned)(s[1])>> 3) & 31) << 8);
    (*m).position.latitude |= (uint32_t)((uint32_t)(((unsigned)(s[2])<< 5) & 224) << 8);
    (*m).position.latitude |= (uint32_t)((uint32_t)(((unsigned)(s[2])>> 3) & 31) << 16);
    (*m).position.latitude |= (uint32_t)((uint32_t)(((unsigned)(s[3])<< 5) & 224) << 16);
    (*m).position.latitude |= (uint32_t)((uint32_t)(((unsigned)(s[3])>> 3) & 31) << 24);
    (*m).position.latitude |= (uint32_t)((uint32_t)(((unsigned)(s[4])<< 5) & 224) << 24);
    (*m).position.longitude |= (uint32_t)(((unsigned)(s[4])>> 3) & 31);
    (*m).position.longitude |= (uint32_t)(((unsigned)(s[5])<< 5) & 224);
    (*m).position.longitude |= (uint32_t)((uint32_t)(((unsigned)(s[5])>> 3) & 31) << 8);
    (*m).position.longitude |= (uint32_t)((uint32_t)(((unsigned)(s[6])<< 5) & 224) << 8);
    (*m).position.longitude |= (uint32_t)((uint32_t)(((unsigned)(s[6])>> 3) & 31) << 16);
    (*m).position.longitude |= (uint32_t)((uint32_t)(((unsigned)(s[7])<< 5) & 224) << 16);
    (*m).position.longitude |= (uint32_t)((uint32_t)(((unsigned)(s[7])>> 3) & 31) << 24);
    (*m).position.longitude |= (uint32_t)((uint32_t)(((unsigned)(s[8])<< 5) & 224) << 24);
    (*m).position.altitude |= (uint32_t)(((unsigned)(s[8])>> 3) & 31);
    (*m).position.altitude |= (uint32_t)(((unsigned)(s[9])<< 5) & 224);
    (*m).position.altitude |= (uint32_t)((uint32_t)(((unsigned)(s[9])>> 3) & 31) << 8);
    (*m).position.altitude |= (uint32_t)((uint32_t)(((unsigned)(s[10])<< 5) & 224) << 8);
    (*m).position.altitude |= (uint32_t)((uint32_t)(((unsigned)(s[10])>> 3) & 31) << 16);
    (*m).position.altitude |= (uint32_t)((uint32_t)(((unsigned)(s[11])<< 5) & 224) << 16);
    (*m).position.altitude |= (uint32_t)((uint32_t)(((unsigned)(s[11])>> 3) & 31) << 24);
    (*m).position.altitude |= (uint32_t)((uint32_t)(((unsigned)(s[12])<< 5) & 224) << 24);
    (*m).flight.pose.yaw |= (int32_t)(((unsigned)(s[12])>> 3) & 31);
    (*m).flight.pose.yaw |= (int32_t)(((unsigned)(s[13])<< 5) & 224);
    (*m).flight.pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[13])>> 3) & 31) << 8);
    (*m).flight.pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[14])<< 5) & 224) << 8);
    (*m).flight.pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[14])>> 3) & 31) << 16);
    (*m).flight.pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[15])<< 5) & 224) << 16);
    (*m).flight.pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[15])>> 3) & 31) << 24);
    (*m).flight.pose.yaw |= (int32_t)((uint32_t)(((unsigned)(s[16])<< 5) & 224) << 24);
    (*m).flight.pose.pitch |= (int32_t)(((unsigned)(s[16])>> 3) & 31);
    (*m).flight.pose.pitch |= (int32_t)(((unsigned)(s[17])<< 5) & 224);
    (*m).flight.pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[17])>> 3) & 31) << 8);
    (*m).flight.pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[18])<< 5) & 224) << 8);
    (*m).flight.pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[18])>> 3) & 31) << 16);
    (*m).flight.pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[19])<< 5) & 224) << 16);
    (*m).flight.pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[19])>> 3) & 31) << 24);
    (*m).flight.pose.pitch |= (int32_t)((uint32_t)(((unsigned)(s[20])<< 5) & 224) << 24);
    (*m).flight.pose.roll |= (int32_t)(((unsigned)(s[20])>> 3) & 31);
    (*m).flight.pose.roll |= (int32_t)(((unsigned)(s[21])<< 5) & 224);
    (*m).flight.pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[21])>> 3) & 31) << 8);
    (*m).flight.pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[22])<< 5) & 224) << 8);
    (*m).flight.pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[22])>> 3) & 31) << 16);
    (*m).flight.pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[23])<< 5) & 224) << 16);
    (*m).flight.pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[23])>> 3) & 31) << 24);
    (*m).flight.pose.roll |= (int32_t)((uint32_t)(((unsigned)(s[24])<< 5) & 224) << 24);
    (*m).flight.velocity[0] |= (int32_t)(((unsigned)(s[24])>> 3) & 31);
    (*m).flight.velocity[0] |= (int32_t)(((unsigned)(s[25])<< 5) & 224);
    (*m).flight.velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[25])>> 3) & 31) << 8);
    (*m).flight.velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[26])<< 5) & 224) << 8);
    (*m).flight.velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[26])>> 3) & 31) << 16);
    (*m).flight.velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[27])<< 5) & 224) << 16);
    (*m).flight.velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[27])>> 3) & 31) << 24);
    (*m).flight.velocity[0] |= (int32_t)((uint32_t)(((unsigned)(s[28])<< 5) & 224) << 24);
    (*m).flight.velocity[1] |= (int32_t)(((unsigned)(s[28])>> 3) & 31);
    (*m).flight.velocity[1] |= (int32_t)(((unsigned)(s[29])<< 5) & 224);
    (*m).flight.velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[29])>> 3) & 31) << 8);
    (*m).flight.velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[30])<< 5) & 224) << 8);
    (*m).flight.velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[30])>> 3) & 31) << 16);
    (*m).flight.velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[31])<< 5) & 224) << 16);
    (*m).flight.velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[31])>> 3) & 31) << 24);
    (*m).flight.velocity[1] |= (int32_t)((uint32_t)(((unsigned)(s[32])<< 5) & 224) << 24);
    (*m).flight.velocity[2] |= (int32_t)(((unsigned)(s[32])>> 3) & 31);
    (*m).flight.velocity[2] |= (int32_t)(((unsigned)(s[33])<< 5) & 224);
    (*m).flight.velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[33])>> 3) & 31) << 8);
    (*m).flight.velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[34])<< 5) & 224) << 8);
    (*m).flight.velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[34])>> 3) & 31) << 16);
    (*m).flight.velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[35])<< 5) & 224) << 16);
    (*m).flight.velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[35])>> 3) & 31) << 24);
    (*m).flight.velocity[2] |= (int32_t)((uint32_t)(((unsigned)(s[36])<< 5) & 224) << 24);
    (*m).flight.acceleration[0] |= (int32_t)(((unsigned)(s[36])>> 3) & 31);
    (*m).flight.acceleration[0] |= (int32_t)(((unsigned)(s[37])<< 5) & 224);
    (*m).flight.acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[37])>> 3) & 31) << 8);
    (*m).flight.acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[38])<< 5) & 224) << 8);
    (*m).flight.acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[38])>> 3) & 31) << 16);
    (*m).flight.acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[39])<< 5) & 224) << 16);
    (*m).flight.acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[39])>> 3) & 31) << 24);
    (*m).flight.acceleration[0] |= (int32_t)((uint32_t)(((unsigned)(s[40])<< 5) & 224) << 24);
    (*m).flight.acceleration[1] |= (int32_t)(((unsigned)(s[40])>> 3) & 31);
    (*m).flight.acceleration[1] |= (int32_t)(((unsigned)(s[41])<< 5) & 224);
    (*m).flight.acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[41])>> 3) & 31) << 8);
    (*m).flight.acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[42])<< 5) & 224) << 8);
    (*m).flight.acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[42])>> 3) & 31) << 16);
    (*m).flight.acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[43])<< 5) & 224) << 16);
    (*m).flight.acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[43])>> 3) & 31) << 24);
    (*m).flight.acceleration[1] |= (int32_t)((uint32_t)(((unsigned)(s[44])<< 5) & 224) << 24);
    (*m).flight.acceleration[2] |= (int32_t)(((unsigned)(s[44])>> 3) & 31);
    (*m).flight.acceleration[2] |= (int32_t)(((unsigned)(s[45])<< 5) & 224);
    (*m).flight.acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[45])>> 3) & 31) << 8);
    (*m).flight.acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[46])<< 5) & 224) << 8);
    (*m).flight.acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[46])>> 3) & 31) << 16);
    (*m).flight.acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[47])<< 5) & 224) << 16);
    (*m).flight.acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[47])>> 3) & 31) << 24);
    (*m).flight.acceleration[2] |= (int32_t)((uint32_t)(((unsigned)(s[48])<< 5) & 224) << 24);
    (*m).propellers[0].id |= (uint8_t)(((unsigned)(s[48])>> 3) & 31);
    (*m).propellers[0].id |= (uint8_t)(((unsigned)(s[49])<< 5) & 224);
    (*m).propellers[0].status |= (PropellerStatus)(((unsigned)(s[49])>> 3) & 3);
    (*m).propellers[0].direction |= (RotatingDirection)(((unsigned)(s[49])>> 5) & 3);
    (*m).propellers[1].id |= (uint8_t)(((unsigned)(s[49])>> 7) & 1);
    (*m).propellers[1].id |= (uint8_t)(((unsigned)(s[50])<< 1) & 254);
    (*m).propellers[1].status |= (PropellerStatus)(((unsigned)(s[50])>> 7) & 1);
    (*m).propellers[1].status |= (PropellerStatus)(((unsigned)(s[51])<< 1) & 2);
    (*m).propellers[1].direction |= (RotatingDirection)(((unsigned)(s[51])>> 1) & 3);
    (*m).propellers[2].id |= (uint8_t)(((unsigned)(s[51])>> 3) & 31);
    (*m).propellers[2].id |= (uint8_t)(((unsigned)(s[52])<< 5) & 224);
    (*m).propellers[2].status |= (PropellerStatus)(((unsigned)(s[52])>> 3) & 3);
    (*m).propellers[2].direction |= (RotatingDirection)(((unsigned)(s[52])>> 5) & 3);
    (*m).propellers[3].id |= (uint8_t)(((unsigned)(s[52])>> 7) & 1);
    (*m).propellers[3].id |= (uint8_t)(((unsigned)(s[53])<< 1) & 254);
    (*m).propellers[3].status |= (PropellerStatus)(((unsigned)(s[53])>> 7) & 1);
    (*m).propellers[3].status |= (PropellerStatus)(((unsigned)(s[54])<< 1) & 2);
    (*m).propellers[3].direction |= (RotatingDirection)(((unsigned)(s[54])>> 1) & 3);
    (*m).power.battery |= (uint8_t)(((unsigned)(s[54])>> 3) & 31);
    (*m).power.battery |= (uint8_t)(((unsigned)(s[55])<< 5) & 224);
    (*m).power.status |= (PowerStatus)(((unsigned)(s[55])>> 3) & 3);
    (*m).power.is_charging |= (bool)(((unsigned)(s[55])>> 5) & 1);
    (*m).network.signal |= (uint8_t)(((unsigned)(s[55])>> 6) & 3);
    (*m).network.signal |= (uint8_t)(((unsigned)(s[56])<< 2) & 12);
    (*m).network.heartbeat_at |= (Timestamp)(((unsigned)(s[56])>> 2) & 63);
    (*m).network.heartbeat_at |= (Timestamp)(((unsigned)(s[57])<< 6) & 192);
    (*m).network.heartbeat_at |= (Timestamp)((uint32_t)(((unsigned)(s[57])>> 2) & 63) << 8);
    (*m).network.heartbeat_at |= (Timestamp)((uint32_t)(((unsigned)(s[58])<< 6) & 192) << 8);
    (*m).network.heartbeat_at |= (Timestamp)((uint32_t)(((unsigned)(s[58])>> 2) & 63) << 16);
    (*m).network.heartbeat_at |= (Timestamp)((uint32_t)(((unsigned)(s[59])<< 6) & 192) << 16);
    (*m).network.heartbeat_at |= (Timestamp)((uint32_t)(((unsigned)(s[59])>> 2) & 63) << 24);
    (*m).network.heartbeat_at |= (Timestamp)((uint32_t)(((unsigned)(s[60])<< 6) & 192) << 24);
    (*m).landing_gear.status |= (LandingGearStatus)(((unsigned)(s[60])>> 2) & 3);
    (*m).pressure_sensor.pressures[0] |= (int32_t)(((unsigned)(s[60])>> 4) & 15);
    (*m).pressure_sensor.pressures[0] |= (int32_t)(((unsigned)(s[61])<< 4) & 240);
    (*m).pressure_sensor.pressures[0] |= (int32_t)((uint32_t)(((unsigned)(s[61])>> 4) & 15) << 8);
    (*m).pressure_sensor.pressures[0] |= (int32_t)((uint32_t)(((unsigned)(s[62])<< 4) & 240) << 8);
    (*m).pressure_sensor.pressures[0] |= (int32_t)((uint32_t)(((unsigned)(s[62])>> 4) & 15) << 16);
    (*m).pressure_sensor.pressures[0] |= (int32_t)((uint32_t)(((unsigned)(s[63])<< 4) & 240) << 16);
    if (((*m).pressure_sensor.pressures[0] >> 23) & 1) (*m).pressure_sensor.pressures[0] |= -16777216;
    (*m).pressure_sensor.pressures[1] |= (int32_t)(((unsigned)(s[63])>> 4) & 15);
    (*m).pressure_sensor.pressures[1] |= (int32_t)(((unsigned)(s[64])<< 4) & 240);
    (*m).pressure_sensor.pressures[1] |= (int32_t)((uint32_t)(((unsigned)(s[64])>> 4) & 15) << 8);
    (*m).pressure_sensor.pressures[1] |= (int32_t)((uint32_t)(((unsigned)(s[65])<< 4) & 240) << 8);
    (*m).pressure_sensor.pressures[1] |= (int32_t)((uint32_t)(((unsigned)(s[65])>> 4) & 15) << 16);
    (*m).pressure_sensor.pressures[1] |= (int32_t)((uint32_t)(((unsigned)(s[66])<< 4) & 240) << 16);
    if (((*m).pressure_sensor.pressures[1] >> 23) & 1) (*m).pressure_sensor.pressures[1] |= -16777216;
    return 0;
}