// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__BASE_H__
#define __BITPROTO__BASE_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

#define MAX_MESSAGE_LENGTH 6

#define HEADER_LENGTH 5

#define MAX_PAYLOAD_LENGTH 1

#if defined(__cplusplus)
}
#endif

#endif