// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "test_bp.h"

void BpXXXProcessArrayMyMessage3(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 1, BpByte());
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayMyMessage3(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 1, BpByte());
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitMyMessage(struct MyMessage *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->payload), BpArray(8, 1 * sizeof(unsigned char), BpXXXProcessArrayMyMessage3, BpXXXJsonFormatArrayMyMessage3), "payload");
}

void BpXXXProcessMyMessage(void *data, struct BpProcessorContext *ctx) {
    struct MyMessage *m = (struct MyMessage *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitMyMessage(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 8, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatMyMessage(void *data, struct BpJsonFormatContext *ctx) {
    struct MyMessage *m = (struct MyMessage *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitMyMessage(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 8, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeMyMessage(struct MyMessage *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessMyMessage((void *)m, &ctx);
    return 0;
}

int DecodeMyMessage(struct MyMessage *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessMyMessage((void *)m, &ctx);
    return 0;
}

int JsonMyMessage(struct MyMessage *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatMyMessage((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitMyPayload(struct MyPayload *m, struct BpMessageFieldDescriptor *fds) {
}

void BpXXXProcessMyPayload(void *data, struct BpProcessorContext *ctx) {
    struct MyPayload *m = (struct MyPayload *)(data);
    struct BpMessageFieldDescriptor field_descriptors[0];
    BpFieldDescriptorsInitMyPayload(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 0, 0, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatMyPayload(void *data, struct BpJsonFormatContext *ctx) {
    struct MyPayload *m = (struct MyPayload *)(data);
    struct BpMessageFieldDescriptor field_descriptors[0];
    BpFieldDescriptorsInitMyPayload(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 0, 0, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeMyPayload(struct MyPayload *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessMyPayload((void *)m, &ctx);
    return 0;
}

int DecodeMyPayload(struct MyPayload *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessMyPayload((void *)m, &ctx);
    return 0;
}

int JsonMyPayload(struct MyPayload *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatMyPayload((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitMyOtherPayload(struct MyOtherPayload *m, struct BpMessageFieldDescriptor *fds) {
}

void BpXXXProcessMyOtherPayload(void *data, struct BpProcessorContext *ctx) {
    struct MyOtherPayload *m = (struct MyOtherPayload *)(data);
    struct BpMessageFieldDescriptor field_descriptors[0];
    BpFieldDescriptorsInitMyOtherPayload(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 0, 0, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatMyOtherPayload(void *data, struct BpJsonFormatContext *ctx) {
    struct MyOtherPayload *m = (struct MyOtherPayload *)(data);
    struct BpMessageFieldDescriptor field_descriptors[0];
    BpFieldDescriptorsInitMyOtherPayload(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 0, 0, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeMyOtherPayload(struct MyOtherPayload *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessMyOtherPayload((void *)m, &ctx);
    return 0;
}

int DecodeMyOtherPayload(struct MyOtherPayload *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessMyOtherPayload((void *)m, &ctx);
    return 0;
}

int JsonMyOtherPayload(struct MyOtherPayload *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatMyOtherPayload((void *)m, &ctx);
    return ctx.n;
}