// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__TEST_H__
#define __BITPROTO__TEST_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include "base_bp.h"

// Number of bytes to encode struct MyMessage
#define BYTES_LENGTH_MY_MESSAGE 1

struct MyMessage {
    // 128
    // ... // Header contents
    unsigned char payload[1]; // 8bit
};

// Number of bytes to encode struct MyPayload
#define BYTES_LENGTH_MY_PAYLOAD 0

struct MyPayload {
};

// Number of bytes to encode struct MyOtherPayload
#define BYTES_LENGTH_MY_OTHER_PAYLOAD 0

struct MyOtherPayload {
};

// Encode struct MyMessage to given buffer s.
int EncodeMyMessage(struct MyMessage *m, unsigned char *s);
// Decode struct MyMessage from given buffer s.
int DecodeMyMessage(struct MyMessage *m, unsigned char *s);
// Format struct MyMessage to a json format string.
int JsonMyMessage(struct MyMessage *m, char *s);

// Encode struct MyPayload to given buffer s.
int EncodeMyPayload(struct MyPayload *m, unsigned char *s);
// Decode struct MyPayload from given buffer s.
int DecodeMyPayload(struct MyPayload *m, unsigned char *s);
// Format struct MyPayload to a json format string.
int JsonMyPayload(struct MyPayload *m, char *s);

// Encode struct MyOtherPayload to given buffer s.
int EncodeMyOtherPayload(struct MyOtherPayload *m, unsigned char *s);
// Decode struct MyOtherPayload from given buffer s.
int DecodeMyOtherPayload(struct MyOtherPayload *m, unsigned char *s);
// Format struct MyOtherPayload to a json format string.
int JsonMyOtherPayload(struct MyOtherPayload *m, char *s);

void BpXXXProcessMyMessage(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatMyMessage(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessMyPayload(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatMyPayload(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessMyOtherPayload(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatMyOtherPayload(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif