"""
bitproto.renderer_c
~~~~~~~~~~~~~~~~~~~~

Renderer for C.
"""

import os
from typing import List

from bitproto.renderer import Renderer
from bitproto.utils import cache, cached_property, write_file


class RendererC(Renderer):
    """Renderer for C language.

    Produces:
        {proto_filename}_bp.h
        {proto_filename}_bp.c
    """

    @cached_property
    def h_out_filepath(self) -> str:
        return self.format_out_filepath(".h")

    @cached_property
    def c_out_filepath(self) -> str:
        return self.format_out_filepath(".c")

    def render(self) -> None:
        self.render_h()
        self.render_c()

    def render_h(self) -> None:
        lines = []
        lines.extend(self.render_proto_docstring())
        # TODO

    def render_c(self) -> None:
        lines = []
        lines.extend(self.render_proto_docstring())
        pass

    @cache
    def render_proto_docstring(self) -> List[str]:
        lines: List[str] = []
        lines.append("// Code generated by bitproto. DO NOT EDIT.")
        lines.append("\n")
        for comment in self.proto.comment_block:
            lines.append("// {0}".format(comment.content()))
        return lines
