// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "example_bp.h"

void BpXXXProcessTimestamp(void *data, struct BpProcessorContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(64));
    BpEndecodeAlias(&descriptor, ctx, data);
}

void BpXXXJsonFormatTimestamp(void *data, struct BpJsonFormatContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(64));
    BpJsonFormatAlias(&descriptor, ctx, data);
}

void BpXXXProcessArrayTernaryInt32(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 3, BpInt(32));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayTernaryInt32(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 3, BpInt(32));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpXXXProcessTernaryInt32(void *data, struct BpProcessorContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpArray(96, 3 * sizeof(int32_t), BpXXXProcessArrayTernaryInt32, BpXXXJsonFormatArrayTernaryInt32));
    BpEndecodeAlias(&descriptor, ctx, data);
}

void BpXXXJsonFormatTernaryInt32(void *data, struct BpJsonFormatContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpArray(96, 3 * sizeof(int32_t), BpXXXProcessArrayTernaryInt32, BpXXXJsonFormatArrayTernaryInt32));
    BpJsonFormatAlias(&descriptor, ctx, data);
}

void BpXXXProcessDroneStatus(void *data, struct BpProcessorContext *ctx) {
    struct BpEnumDescriptor descriptor = BpEnumDescriptor(BpUint(3));
    BpEndecodeEnum(&descriptor, ctx, data);
}

void BpXXXJsonFormatDroneStatus(void *data, struct BpJsonFormatContext *ctx) {
    struct BpEnumDescriptor descriptor = BpEnumDescriptor(BpUint(3));
    BpJsonFormatEnum(&descriptor, ctx, data);
}

void BpXXXProcessPropellerStatus(void *data, struct BpProcessorContext *ctx) {
    struct BpEnumDescriptor descriptor = BpEnumDescriptor(BpUint(2));
    BpEndecodeEnum(&descriptor, ctx, data);
}

void BpXXXJsonFormatPropellerStatus(void *data, struct BpJsonFormatContext *ctx) {
    struct BpEnumDescriptor descriptor = BpEnumDescriptor(BpUint(2));
    BpJsonFormatEnum(&descriptor, ctx, data);
}

void BpXXXProcessRotatingDirection(void *data, struct BpProcessorContext *ctx) {
    struct BpEnumDescriptor descriptor = BpEnumDescriptor(BpUint(2));
    BpEndecodeEnum(&descriptor, ctx, data);
}

void BpXXXJsonFormatRotatingDirection(void *data, struct BpJsonFormatContext *ctx) {
    struct BpEnumDescriptor descriptor = BpEnumDescriptor(BpUint(2));
    BpJsonFormatEnum(&descriptor, ctx, data);
}

void BpXXXProcessPowerStatus(void *data, struct BpProcessorContext *ctx) {
    struct BpEnumDescriptor descriptor = BpEnumDescriptor(BpUint(2));
    BpEndecodeEnum(&descriptor, ctx, data);
}

void BpXXXJsonFormatPowerStatus(void *data, struct BpJsonFormatContext *ctx) {
    struct BpEnumDescriptor descriptor = BpEnumDescriptor(BpUint(2));
    BpJsonFormatEnum(&descriptor, ctx, data);
}

void BpXXXProcessLandingGearStatus(void *data, struct BpProcessorContext *ctx) {
    struct BpEnumDescriptor descriptor = BpEnumDescriptor(BpUint(2));
    BpEndecodeEnum(&descriptor, ctx, data);
}

void BpXXXJsonFormatLandingGearStatus(void *data, struct BpJsonFormatContext *ctx) {
    struct BpEnumDescriptor descriptor = BpEnumDescriptor(BpUint(2));
    BpJsonFormatEnum(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitPropeller(struct Propeller *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->id), BpUint(8), "id");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->status), BpEnum(2, sizeof(PropellerStatus), BpXXXProcessPropellerStatus, BpXXXJsonFormatPropellerStatus), "status");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->direction), BpEnum(2, sizeof(RotatingDirection), BpXXXProcessRotatingDirection, BpXXXJsonFormatRotatingDirection), "direction");
}

void BpXXXProcessPropeller(void *data, struct BpProcessorContext *ctx) {
    struct Propeller *m = (struct Propeller *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitPropeller(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 12, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatPropeller(void *data, struct BpJsonFormatContext *ctx) {
    struct Propeller *m = (struct Propeller *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitPropeller(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 12, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodePropeller(struct Propeller *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessPropeller((void *)m, &ctx);
    return 0;
}

int DecodePropeller(struct Propeller *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessPropeller((void *)m, &ctx);
    return 0;
}

int JsonPropeller(struct Propeller *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatPropeller((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitPower(struct Power *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->battery), BpUint(8), "battery");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->status), BpEnum(2, sizeof(PowerStatus), BpXXXProcessPowerStatus, BpXXXJsonFormatPowerStatus), "status");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->is_charging), BpBool(), "is_charging");
}

void BpXXXProcessPower(void *data, struct BpProcessorContext *ctx) {
    struct Power *m = (struct Power *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitPower(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 11, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatPower(void *data, struct BpJsonFormatContext *ctx) {
    struct Power *m = (struct Power *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitPower(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 11, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodePower(struct Power *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessPower((void *)m, &ctx);
    return 0;
}

int DecodePower(struct Power *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessPower((void *)m, &ctx);
    return 0;
}

int JsonPower(struct Power *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatPower((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitNetwork(struct Network *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->signal), BpUint(4), "signal");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->heartbeat_at), BpAlias(64, sizeof(Timestamp), BpXXXProcessTimestamp, BpXXXJsonFormatTimestamp), "heartbeat_at");
}

void BpXXXProcessNetwork(void *data, struct BpProcessorContext *ctx) {
    struct Network *m = (struct Network *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitNetwork(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 68, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatNetwork(void *data, struct BpJsonFormatContext *ctx) {
    struct Network *m = (struct Network *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitNetwork(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 68, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeNetwork(struct Network *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessNetwork((void *)m, &ctx);
    return 0;
}

int DecodeNetwork(struct Network *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessNetwork((void *)m, &ctx);
    return 0;
}

int JsonNetwork(struct Network *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatNetwork((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitLandingGear(struct LandingGear *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->status), BpEnum(2, sizeof(LandingGearStatus), BpXXXProcessLandingGearStatus, BpXXXJsonFormatLandingGearStatus), "status");
}

void BpXXXProcessLandingGear(void *data, struct BpProcessorContext *ctx) {
    struct LandingGear *m = (struct LandingGear *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitLandingGear(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 2, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatLandingGear(void *data, struct BpJsonFormatContext *ctx) {
    struct LandingGear *m = (struct LandingGear *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitLandingGear(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 2, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeLandingGear(struct LandingGear *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessLandingGear((void *)m, &ctx);
    return 0;
}

int DecodeLandingGear(struct LandingGear *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessLandingGear((void *)m, &ctx);
    return 0;
}

int JsonLandingGear(struct LandingGear *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatLandingGear((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitPosition(struct Position *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->latitude), BpUint(32), "latitude");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->longitude), BpUint(32), "longitude");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->altitude), BpUint(32), "altitude");
}

void BpXXXProcessPosition(void *data, struct BpProcessorContext *ctx) {
    struct Position *m = (struct Position *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitPosition(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 96, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatPosition(void *data, struct BpJsonFormatContext *ctx) {
    struct Position *m = (struct Position *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitPosition(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 96, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodePosition(struct Position *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessPosition((void *)m, &ctx);
    return 0;
}

int DecodePosition(struct Position *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessPosition((void *)m, &ctx);
    return 0;
}

int JsonPosition(struct Position *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatPosition((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitPose(struct Pose *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->yaw), BpInt(32), "yaw");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->pitch), BpInt(32), "pitch");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->roll), BpInt(32), "roll");
}

void BpXXXProcessPose(void *data, struct BpProcessorContext *ctx) {
    struct Pose *m = (struct Pose *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitPose(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 96, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatPose(void *data, struct BpJsonFormatContext *ctx) {
    struct Pose *m = (struct Pose *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitPose(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 96, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodePose(struct Pose *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessPose((void *)m, &ctx);
    return 0;
}

int DecodePose(struct Pose *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessPose((void *)m, &ctx);
    return 0;
}

int JsonPose(struct Pose *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatPose((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitFlight(struct Flight *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->pose), BpMessage(96, sizeof(struct Pose), BpXXXProcessPose, BpXXXJsonFormatPose), "pose");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->velocity), BpAlias(96, sizeof(TernaryInt32), BpXXXProcessTernaryInt32, BpXXXJsonFormatTernaryInt32), "velocity");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->acceleration), BpAlias(96, sizeof(TernaryInt32), BpXXXProcessTernaryInt32, BpXXXJsonFormatTernaryInt32), "acceleration");
}

void BpXXXProcessFlight(void *data, struct BpProcessorContext *ctx) {
    struct Flight *m = (struct Flight *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitFlight(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 288, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatFlight(void *data, struct BpJsonFormatContext *ctx) {
    struct Flight *m = (struct Flight *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitFlight(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 288, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeFlight(struct Flight *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessFlight((void *)m, &ctx);
    return 0;
}

int DecodeFlight(struct Flight *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessFlight((void *)m, &ctx);
    return 0;
}

int JsonFlight(struct Flight *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatFlight((void *)m, &ctx);
    return ctx.n;
}

void BpXXXProcessArrayDrone4(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 4, BpMessage(12, sizeof(struct Propeller), BpXXXProcessPropeller, BpXXXJsonFormatPropeller));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayDrone4(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 4, BpMessage(12, sizeof(struct Propeller), BpXXXProcessPropeller, BpXXXJsonFormatPropeller));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitDrone(struct Drone *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->status), BpEnum(3, sizeof(DroneStatus), BpXXXProcessDroneStatus, BpXXXJsonFormatDroneStatus), "status");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->position), BpMessage(96, sizeof(struct Position), BpXXXProcessPosition, BpXXXJsonFormatPosition), "position");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->flight), BpMessage(288, sizeof(struct Flight), BpXXXProcessFlight, BpXXXJsonFormatFlight), "flight");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->propellers), BpArray(48, 4 * sizeof(struct Propeller), BpXXXProcessArrayDrone4, BpXXXJsonFormatArrayDrone4), "propellers");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->power), BpMessage(11, sizeof(struct Power), BpXXXProcessPower, BpXXXJsonFormatPower), "power");
    fds[5] = BpMessageFieldDescriptor((void *)&(m->network), BpMessage(68, sizeof(struct Network), BpXXXProcessNetwork, BpXXXJsonFormatNetwork), "network");
    fds[6] = BpMessageFieldDescriptor((void *)&(m->landing_gear), BpMessage(2, sizeof(struct LandingGear), BpXXXProcessLandingGear, BpXXXJsonFormatLandingGear), "landing_gear");
}

void BpXXXProcessDrone(void *data, struct BpProcessorContext *ctx) {
    struct Drone *m = (struct Drone *)(data);
    struct BpMessageFieldDescriptor field_descriptors[7];
    BpFieldDescriptorsInitDrone(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 7, 516, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatDrone(void *data, struct BpJsonFormatContext *ctx) {
    struct Drone *m = (struct Drone *)(data);
    struct BpMessageFieldDescriptor field_descriptors[7];
    BpFieldDescriptorsInitDrone(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 7, 516, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeDrone(struct Drone *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessDrone((void *)m, &ctx);
    return 0;
}

int DecodeDrone(struct Drone *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessDrone((void *)m, &ctx);
    return 0;
}

int JsonDrone(struct Drone *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatDrone((void *)m, &ctx);
    return ctx.n;
}